### ISSUE TITLE
Unable to install on windows 10 x64.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [diamondio/better-queue-sqlite#4]
```npm install sqlite3
npm install better-queue-sqlite```

Multiple recent versions of node.js.

Sqlite3 dependency too old? not found, would updating dependency version in package.json to ```^4.1.1``` resolve this?


```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.1/node-v72-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.1 and node@12.14.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.1 and node@12.14.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  unpack_sqlite_dep
  sqlite3.c
  sqlite3.c
C:\bob\node_modules\better-queue-sqlite\node_modules\sqlite3\build\Release\obj\global_intermediate\sqlite-autoconf-3240000\sqlite3.c : fatal error C1083: Cannot open compiler generated file: 'C:\bob\node_modules\better-queue-sqlite\node
_modules\sqlite3\build\deps\Release\obj\sqlite3\sqlite3.obj': Permission denied [C:\bob\node_modules\better-queue-sqlite\node_modules\sqlite3\build\deps\sqlite3.vcxproj]
```

**Comment by LiamKarlMitchell** [comment]
Ended up copying entire git repo into a folder and changing the dependency version so it matched other libraries I am using that also use sqlite.
Worked fine :)

**Comment by prithvin** [comment]
https://stackoverflow.com/questions/33154696/msbuild-error-the-builds-tools-for-v140-platform-toolset-v140-cannot-be-f 
top soln. worked perfectly for me
